### ISSUE TITLE
Location Profile: We need to build a location profile. e.g. Hole in the wall cafe - here one may find 10 books to Read.

### ISSUE THREAD

**Issue by sunboo** [barterli/barter.li#10]
Eventually this may be one of the ways to make our platform sustainable via some revenue.

**Comment by suras** [comment]
at present user location is mapped to books. but it would be better to map locations to books
like book belongs to a location. in previous method there will be lot of queries to get book available at a location but later seems to be efficient. And also i filtered foursquare api to show only verified address locations.

**Comment by sunboo** [comment]
Yes I agree. It will be a good idea to run this through a data base expert.

1) If the user changes his location then all his books should be auto-reassigned the location.
