### ISSUE TITLE
API documentation

### ISSUE THREAD

**Issue by vinaysshenoy** [barterli/barter.li#17]
We need some sort of a web page which includes all the API endpoints, their request formats and sample responses.

**Comment by sunboo** [comment]
Suren! Communication 101 :)

**Comment by kirthi35** [comment]
We should use MediaWiki and Document everything over there
.

**Comment by suras** [comment]
https://gist.github.com/suras/9089279

**Comment by suras** [comment]
i will be using yard for documentation
