### ISSUE TITLE
Issue Management for barter.li

### ISSUE THREAD

**Issue by vinaysshenoy** [barterli/barter.li#21]
I just figured out a way we might be able to make issue management simple, free and easy for barter.li. Since it's an open-source community project, there's no point in integrating a professional customer support library.

Github has an API which we can use to create Issues. How about we just integrate the API into the Android client and use it to generate issues by users if they have problems? It should make things a lot simpler.

@suras , @SujeetSimply , @infinitec123 , @kirthi35 Please give your inputs as well.

**Comment by vinaysshenoy** [comment]
Oh, the endpoint is http://developer.github.com/v3/issues/#create-an-issue

**Comment by suras** [comment]
done
