### ISSUE TITLE
Register/Login API combine

### ISSUE THREAD

**Issue by vinaysshenoy** [barterli/barter.li#24]
We need to combine register/login flows into a single API. Basically, we'll call log in with one of the following three configurations - 

"type":"manual"/"facebook"/"google"
"accessToken":" //For type = facebook or google
OR
"email":"", "pasword:" //for type = "manual"

At that point, you need to check if user is already there in database. If yes, return the authentication token + user info, if no, create the user and return the authentication token + user info.

This will enable best UX as we don't need separate register/login flows on client side.

**Comment by suras** [comment]
done
