### ISSUE TITLE
Preferred Location format upgrade

### ISSUE THREAD

**Issue by vinaysshenoy** [barterli/barter.li#25]
Whenever we use location in the API(Preferred location, Location for a book, etc), is it possible to send it in this way - 

"preferred_location": {
  id: "4bcd805cfb84c9b61512223e", -> Location Id in barter.li
  fq_id:"", -> If it is a foursquare venu, the foursquare Id 
  name: "UB City",
  address: "at Vittal Mallya Rd",
  lat: 12.971814708809388,
  lng: 77.5958776473999,
  postalCode: "560001",
  cc: "IN",
  city: ",Bangalore",
  state: "Karnātaka",
  country: "India"
}

Using this, on the client side, we can format the display easily.

**Comment by vinaysshenoy** [comment]
Even when searching books, the location parameter should be updated for this format.

**Comment by suras** [comment]
is postal code and country code necessary?.  i think it will be better if you geocode the address based on user location in client side and send me the details and also call foursquare directly from android so we can avoid unnecessary server calls

**Comment by vinaysshenoy** [comment]
No, I'm not asking for postal code and CC. That's just an example.

What is important for me are the following fields - id, fq_id(if exists), name, address, lat, lng

This is because when displaying search results, I can add a little line to every search result -  "find at UB City, Vittal Mallya Road".

If you can get the Street, and Cross Street from FQ as well, that will be awesome too. The thing is, I won't be reverse geododing from the lat/lng until the user goes into book details, to prevent unecessary API calls. Whatever you can give me in server response will be great as it will make the UX smooth.

**Comment by suras** [comment]
i taught of getting user location details along with latitude and longitude in one api request instead of me again geocoding with latitude and longitude

**Comment by vinaysshenoy** [comment]
That's ok, but we won't be able to show the preferred location on the home
page for books. This is what we can do -
1. If user sets preferred location using Foursquare venues, it's no
   problem because we will get all those details with foursquare objects
2. If user decides to use custom location for preferred location, the
   client will reverse geocode it.

In either case, the client will have the full address at the time of
setting the preferred location. The client can send this info to you along
with lat/long when setting user preferred location. If we do this, there
won't be any problem in sending this along with book info, right? Because
user preferred location will be same as book preferred location.

The same procedure can be followed in future when we enable individual
preferred locations for books.

On Mon, Mar 24, 2014 at 5:54 PM, surendar notifications@github.com wrote:

> i taught of getting user location details along with latitude and
> longitude in one api request instead of me again geocoding with latitude
> and longitude
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/barterli/barter.li/issues/25#issuecomment-38437603
> .

## 

Vinay S Shenoy
Software Engineer | Sourcebits LLC, Electronic City, Bangalore
+91-9538122356 | vinaysshenoy@gmail.com
LinkedIn : http://in.linkedin.com/in/vinaysshenoy

**Comment by suras** [comment]
individual book location is already enabled just send location{latitude, longitude, country, city ,state. address}along with creating book if no location param present then default user preferred location will be used

**Comment by vinaysshenoy** [comment]
Awesome. Can we do the same for User preferred location then?

On Mon, Mar 24, 2014 at 6:06 PM, surendar notifications@github.com wrote:

> individual book location is already enabled just send location{latitude,
> longitude, country, city ,state. address}along with creating book if no
> location param present then default user preferred location will be used
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/barterli/barter.li/issues/25#issuecomment-38438624
> .

## 

Vinay S Shenoy
Software Engineer | Sourcebits LLC, Electronic City, Bangalore
+91-9538122356 | vinaysshenoy@gmail.com
LinkedIn : http://in.linkedin.com/in/vinaysshenoy

**Comment by suras** [comment]
cant understand. you can change the user preferred location by post 'api/v1/user_preferred_location'
doing so deletes the existing location and creates the new one. and also locations will created onlf if longitude and latitude are unique if not existing will be reused

**Comment by vinaysshenoy** [comment]
I think in current API, preferred location is being sent as null for books
search. Can you add a sample location object so I can see what is coming?

On Mon, Mar 24, 2014 at 6:14 PM, surendar notifications@github.com wrote:

> cant understand. you can change the user preferred location by post
> 'api/v1/user_preferred_location'
> doing so deletes the existing location and creates the new one. and also
> locations will created onlf if longitude and latitude are unique if not
> existing will be reused
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/barterli/barter.li/issues/25#issuecomment-38439336
> .

## 

Vinay S Shenoy
Software Engineer | Sourcebits LLC, Electronic City, Bangalore
+91-9538122356 | vinaysshenoy@gmail.com
LinkedIn : http://in.linkedin.com/in/vinaysshenoy

**Comment by vinaysshenoy** [comment]
Never mind. I saw the API response on the other post. Street/Address/name
won't be coming as null for most places, right?

On Mon, Mar 24, 2014 at 6:28 PM, Vinay Shenoy vinaysshenoy@gmail.comwrote:

> I think in current API, preferred location is being sent as null for books
> search. Can you add a sample location object so I can see what is coming?
> 
> On Mon, Mar 24, 2014 at 6:14 PM, surendar notifications@github.comwrote:
> 
> > cant understand. you can change the user preferred location by post
> > 'api/v1/user_preferred_location'
> > doing so deletes the existing location and creates the new one. and also
> > locations will created onlf if longitude and latitude are unique if not
> > existing will be reused
> > 
> > ## 
> > 
> > Reply to this email directly or view it on GitHubhttps://github.com/barterli/barter.li/issues/25#issuecomment-38439336
> > .
> 
> ## 
> 
> Vinay S Shenoy
> Software Engineer | Sourcebits LLC, Electronic City, Bangalore
> +91-9538122356 | vinaysshenoy@gmail.com
> LinkedIn : http://in.linkedin.com/in/vinaysshenoy

## 

Vinay S Shenoy
Software Engineer | Sourcebits LLC, Electronic City, Bangalore
+91-9538122356 | vinaysshenoy@gmail.com
LinkedIn : http://in.linkedin.com/in/vinaysshenoy

**Comment by suras** [comment]
right now i  am not reverse geocoding so null is given since country, state , city will come from client

**Comment by vinaysshenoy** [comment]
Not a problem. I'll send it.
