### ISSUE TITLE
Search radius required for search endpoint

### ISSUE THREAD

**Issue by vinaysshenoy** [barterli/barter.li#26]
Currently, the search API uses only latitude/longitude parameters. We also need to be able to send a search radius(preferably in metres) which we can use when user zooms in/zooms out the map.

**Comment by suras** [comment]
done send params as radius (i set the default as 100 mile if radius not present)

**Comment by vinaysshenoy** [comment]
In miles? Can we use in metres instead? User might zoom to very low level in Map.

**Comment by suras** [comment]
no only km or miles. i changed it to km.

**Comment by vinaysshenoy** [comment]
Hmm. I can send 0. values for km?

**Comment by suras** [comment]
i will check this and let you know. i think at first we don't have that much books available at first. so we need to have a default that is of larger radius

**Comment by vinaysshenoy** [comment]
Yeah, it's not a priority. As long as we can search as low as 1 km, it should be more than enough for now.

**Comment by vinaysshenoy** [comment]
Also one more issue. Right now, it requires search parameter. Can you make that also optional? It should work like this - 
- search,lat,long,radius -> Return all books matching the name, centered at lat/lng/ within radius km
- lat,long,radius - Return all books centered at lat/long within radius km
- search, but one of the other parameters - discard the other params, keep only the search
- nothing - return books according to rating or something(in future, check if you can user's location from IP address and use that instead)

For the home screen, we need something to show on first launch. For that, we require the second form of the API.

Also, what is the limit on the items returning from API. We need to add a limit so that the response doesn't take too much time. In future, we'll need to add pagination.

**Comment by suras** [comment]
everything is optional
