### ISSUE TITLE
Images for Books

### ISSUE THREAD

**Issue by vinaysshenoy** [barterli/barter.li#27]
Books are not sending any image urls. Is it possible to add? Even dummy images are fine, just give two or three different ones.

**Comment by suras** [comment]
added default url to images

**Comment by vinaysshenoy** [comment]
Pushed to server? I'm still getting null :-)

**Comment by suras** [comment]
no wait  for sometime

**Comment by suras** [comment]
yes pushed to server

**Comment by vinaysshenoy** [comment]
It took two hours to push???

On Mon, Mar 24, 2014 at 5:48 PM, surendar notifications@github.com wrote:

> yes pushed to server
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/barterli/barter.li/issues/27#issuecomment-38437170
> .

## 

Vinay S Shenoy
Software Engineer | Sourcebits LLC, Electronic City, Bangalore
+91-9538122356 | vinaysshenoy@gmail.com
LinkedIn : http://in.linkedin.com/in/vinaysshenoy

**Comment by suras** [comment]
the delay was due to cleaning unnecesary database tables and securing rabbitmq  at server with permissions
are you using 162.243.198.171:3000 or 162.243.198.171.    i haved stopped 162.243.198.171:3000.
use 162.243.198.171.

also asking for books now gives its location and tags

{
    "status": "success",
    "book": {
        "id": 2,
        "title": "rails",
        "author": null,
        "isbn_10": null,
        "isbn_13": null,
        "edition": null,
        "print": null,
        "publication_year": null,
        "publication_month": null,
        "condition": null,
        "value": null,
        "status": null,
        "stage": null,
        "description": null,
        "visits": null,
        "user_id": 14,
        "prefered_place": null,
        "prefered_time": null,
        "created_at": "2014-03-24T12:13:13.120Z",
        "updated_at": "2014-03-24T12:13:13.120Z",
        "rating": null,
        "image": {
            "url": "/fallback/1_default.png"
        },
        "publisher": null,
        "goodreads_id": null,
        "image_url": "/fallback/1_default.png",
        "pages": null,
        "language_code": null,
        "barter_type": null,
        "location_id": 1,
        "location": {
            "id": 1,
            "country": null,
            "state": null,
            "city": null,
            "address": null,
            "postal_code": null,
            "locality": null,
            "name": null,
            "latitude": "12.453454",
            "longitude": "12.3445",
            "created_at": "2014-03-24T12:12:12.000Z",
            "updated_at": "2014-03-24T12:12:12.000Z"
        },
        "tags": [
            {
                "id": 1,
                "name": "free",
                "created_at": "2014-03-24T11:38:36.000Z",
                "updated_at": "2014-03-24T11:38:36.000Z"
            }
        ]
    }
}

**Comment by vinaysshenoy** [comment]
Can you use the fully qualified url for the images instead of relative? The reason is that for the final app, we'll probably need a dedicated file server.

**Comment by suras** [comment]
yes

**Comment by suras** [comment]
done
