### ISSUE TITLE
Keys for Barter Type

### ISSUE THREAD

**Issue by vinaysshenoy** [barterli/barter.li#28]
barter_type is CSV string, right? What are the keys for the different barter types?

**Comment by suras** [comment]
call this api /api/v1/tags 
output example [{id:1, name:free}, {id:2, name:free}] then while creating book send the ids like tag_ids:[1,2]

**Comment by vinaysshenoy** [comment]
That's not a good way, because the tags are hardcoded on client end. The flow with this will cause a lot of issues, for example, if pulling tags fails.

If you can tell me which tag id are associated with which barter type is associated with which tag, I can add it into the app. In any case, the types of tags will not change often.

**Comment by suras** [comment]
free, sale, barter, private, rent, read

send the name itself otherwise tag_names[free, barter]

**Comment by vinaysshenoy** [comment]
If I want to create barter_type for a book, how will I send it?

AFAIK, it's "barter_type": [free,barter] as a key in the book json. Is this correct?

Also, please sent it to client in the same way so it is easier to parse.

**Comment by suras** [comment]
yes   book{barter_type:[free, barter]}. i will be using jbuilder gem tomorrow so you can tell me exactly how the output should be so it will be easy for you

**Comment by vinaysshenoy** [comment]
Awesome. I'll leave the parsing for this until tomorrow then. I'll come to the workplace tomorrow morning and we'll set it up.
