### ISSUE TITLE
Fix id generation in APIs

### ISSUE THREAD

**Issue by vinaysshenoy** [barterli/barter.li#29]
Currently, in all the API responses, for IDs(user Id, book Id, location Id), the id being sent is an integer. I'm guessing this is the database row id.

Please don't do this way. Keep the database row Ids internal to the server. Instead, generate unique string Ids for every new user/book/location and use that in API responses. This needs to be done before alpha launch.

**Comment by suras** [comment]
why we need string ids? any specific reason

**Comment by sourcebits-ajmal** [comment]
May be a timestamp + random number b/w (100..999) may give a fancy looking string that can be added to every table upon insertion, but does this have any impact on the security of the APP?

**Comment by vinaysshenoy** [comment]
Nope. But the problem will happen if database migration is done, let''s
say, switching servers or changing the underlying database.

The DB row ids for individual user Ids might change, which will render the
clients unoperable. If we instead generate string ids separately, the
database on server end can be separated from the app.

On Wed, Mar 26, 2014 at 4:29 PM, Sourcebits-Ajmal
notifications@github.comwrote:

> Does this make any impact on the security of the app?
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/barterli/barter.li/issues/29#issuecomment-38670731
> .

## 

Vinay S Shenoy
Software Engineer | Sourcebits LLC, Electronic City, Bangalore
+91-9538122356 | vinaysshenoy@gmail.com
LinkedIn : http://in.linkedin.com/in/vinaysshenoy

**Comment by vinaysshenoy** [comment]
I'm just making it clear that I don't want a generated string as the
ID(although that would be preferable). I just want something separate from
the database row id to be used as the identifier on the client side.

Something that will remain constant across database changes/server
upgrades, etc.

On Wed, Mar 26, 2014 at 4:32 PM, Vinay Shenoy vinaysshenoy@gmail.comwrote:

> Nope. But the problem will happen if database migration is done, let''s
> say, switching servers or changing the underlying database.
> 
> The DB row ids for individual user Ids might change, which will render the
> clients unoperable. If we instead generate string ids separately, the
> database on server end can be separated from the app.
> 
> On Wed, Mar 26, 2014 at 4:29 PM, Sourcebits-Ajmal <
> notifications@github.com> wrote:
> 
> > Does this make any impact on the security of the app?
> > 
> > ## 
> > 
> > Reply to this email directly or view it on GitHubhttps://github.com/barterli/barter.li/issues/29#issuecomment-38670731
> > .
> 
> ## 
> 
> Vinay S Shenoy
> Software Engineer | Sourcebits LLC, Electronic City, Bangalore
> +91-9538122356 | vinaysshenoy@gmail.com
> LinkedIn : http://in.linkedin.com/in/vinaysshenoy

## 

Vinay S Shenoy
Software Engineer | Sourcebits LLC, Electronic City, Bangalore
+91-9538122356 | vinaysshenoy@gmail.com
LinkedIn : http://in.linkedin.com/in/vinaysshenoy

**Comment by suras** [comment]
right now query is based on ids.(then i have to change everything based on it with is unnecesssary right now).  even if we change the database we can retain the ids that's not an issue. i think no apis right now is based purely on ids for client side to work. 
what are the exact uses cases you will be storing ids on client side and sending to server

**Comment by vinaysshenoy** [comment]
When books are fetched, book id, the user id associated with the book, the
location id are all db row ids.

It's fine for the alpha lunch, but this is a must fix for the beta launch.
It's important that the implementation details of the server are kept
separate from the client. In the off chance that the DB row ids cannot be
maintained during a migration, the clients will all fail unless they clear
the app data and refetch everything, which is a big no-no for UX.

On Wed, Mar 26, 2014 at 5:40 PM, surendar notifications@github.com wrote:

> right now query is based on ids.(then i have to change everything based on
> it with is unnecesssary right now). even if we change the database we can
> retain the ids that's not an issue. i think no apis right now is based
> purely on ids for client side to work.
> what are the exact uses cases you will be storing ids on client side and
> sending to server
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/barterli/barter.li/issues/29#issuecomment-38676015
> .

## 

Vinay S Shenoy
Software Engineer | Sourcebits LLC, Electronic City, Bangalore
+91-9538122356 | vinaysshenoy@gmail.com
LinkedIn : http://in.linkedin.com/in/vinaysshenoy

**Comment by barter** [comment]
Guys

Seems important enough to go on Beta for sure.

Pj

**Comment by suras** [comment]
yes done see #32
