### ISSUE TITLE
Location object is user sign in response is sent as String instead of JSONObject

### ISSUE THREAD

**Issue by vinaysshenoy** [barterli/barter.li#31]
When I signed into the account, I got the response 
`{"user":       {"id":2,"email":"vinaysshenoy@gmail.com","description":null,"first_name":null,"last_name":null,"location":"","auth_token":"s5p4JDkexKspVgcxkXNd","sign_in_count":0}}
`

The location object is coming as a String instead of a JSONObject. Please fix this.

**Comment by suras** [comment]
i gives location json object only if a preferred location is set.

**Comment by vinaysshenoy** [comment]
That's a problem when we parse. Can you send null instead? or an empty Json object.

**Comment by suras** [comment]
yes done.

**Comment by vinaysshenoy** [comment]
Thanks.

On Thu, Mar 27, 2014 at 12:04 PM, surendar notifications@github.com wrote:

> yes done.
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/barterli/barter.li/issues/31#issuecomment-38772953
> .

## 

Vinay S Shenoy
Software Engineer | Sourcebits LLC, Electronic City, Bangalore
+91-9538122356 | vinaysshenoy@gmail.com
LinkedIn : http://in.linkedin.com/in/vinaysshenoy

**Comment by vinaysshenoy** [comment]
This is not done. I'm still getting a string.

**Comment by suras** [comment]
i never  pushed to server. i am in process of changing things to string_id

**Comment by suras** [comment]
done
