### ISSUE TITLE
Renaming the id fields

### ISSUE THREAD

**Issue by vinaysshenoy** [barterli/barter.li#32]
Can the id fields for individual objects types be renamed to be more specifc?

Currently, whether the object is a user, location or book, all the "id" fields are being sent as "id". It would be preferable to make it more specific, i.e., "user_id" for user, "location_id" for a location, etc.

This is also related to this issue https://github.com/barterli/barter.li/issues/29

If we can get both done simultaneously for the beta launch, it would be great.

**Comment by suras** [comment]
i cant use user_id as it is required for doing relations with models i have used id_user, id_book, id_location.  i have generate a string id like this "34_caad830ac7" where 34 corresponds to row id

**Comment by vinaysshenoy** [comment]
Not an issue. Although I don't like that 34_ at the beginning. Why do we
need that?

**Comment by suras** [comment]
we can easily identify the row id from that if for some reasons we need to know the row id from the unique id. and also i dont need to check the database if the generated id is unique and not used by others as i am using the unique row id as prefix

**Comment by vinaysshenoy** [comment]
Then it has no difference at all. The db row id shouldn't be communicated
in the API response in any form. ID should be totally disconnected from row
ID.

As for the uniqueness constraint, just add a uniqueness constraint to the
field in the DB. Generate the random string id, and save it. Second, as
long as your ID generation algorithm is proper, you shouldn't need to worry
about uniqueness. We know that the id will be generated only during user
creation. If that's the case, the email ID will be unique as we know it
already isn't there in the DB. The id for the user can be an SHA1 hash of
the email id as it's only used for identification, not authentication.

On Fri, Mar 28, 2014 at 2:27 PM, surendar notifications@github.com wrote:

> we can easily identify the row id from that if for some reasons we need to
> know the row id from the unique id. and also i dont need to check the
> database if the generated id is unique and not used by others as i am using
> the unique row id as prefix
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/barterli/barter.li/issues/32#issuecomment-38899087
> .

## 

Vinay S Shenoy
Software Engineer | Sourcebits LLC, Electronic City, Bangalore
+91-9538122356 | vinaysshenoy@gmail.com
LinkedIn : http://in.linkedin.com/in/vinaysshenoy

**Comment by suras** [comment]
can u explain clearly why row ids should not be communicated in api event if it is indirect.  i have used row id just for convention

**Comment by vinaysshenoy** [comment]
The thing is, it's not a best practice. The client shouldn't care what
implementation the server has, one when you sent the db row id to client,
you are exposing some of that implementation to client.

Second, the identifier should be separated from the implementation again.
The identifier is what will keep the server->client binding intact even if
the underlying database has changed. If you use even a part of the
identifier to directly access the database, there is a chance of failure.
And I'm sure there will be security issues as well if you directly give the
row id.

You can check most of the API providers. Facebook, Google, Twitter,
Foursquare, none of them do this way.

On Fri, Mar 28, 2014 at 3:11 PM, surendar notifications@github.com wrote:

> can u explain clearly why row ids should not be communicated in api event
> if it is indirect. i have used row id just for convention
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/barterli/barter.li/issues/32#issuecomment-38902060
> .

## 

Vinay S Shenoy
Software Engineer | Sourcebits LLC, Electronic City, Bangalore
+91-9538122356 | vinaysshenoy@gmail.com
LinkedIn : http://in.linkedin.com/in/vinaysshenoy

**Comment by suras** [comment]
ok

**Comment by vinaysshenoy** [comment]
http://blog.codinghorror.com/primary-keys-ids-versus-guids/

On Fri, Mar 28, 2014 at 3:36 PM, surendar notifications@github.com wrote:

> ok
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/barterli/barter.li/issues/32#issuecomment-38903757
> .

## 

Vinay S Shenoy
Software Engineer | Sourcebits LLC, Electronic City, Bangalore
+91-9538122356 | vinaysshenoy@gmail.com
LinkedIn : http://in.linkedin.com/in/vinaysshenoy

**Comment by suras** [comment]
i will be using string ids for querys from now and internally integer id as primary key
http://blog.codinghorror.com/primary-keys-ids-versus-guids/
this is about using guid as primary key which i cannot use now as many rails gems are tied to integer primary key. mongodb and other nosql dbs uses this kind of keys as(_id) so it works great in distributed models. but relational db it may or may not be good fit. there are pros and cons of both.  lets close this issue right now

**Comment by vinaysshenoy** [comment]
Right. We'll discuss this after alpha release and discuss what to do.

On Fri, Mar 28, 2014 at 3:55 PM, surendar notifications@github.com wrote:

> i will be using string ids for querys from now and internally integer id
> as primary key
> http://blog.codinghorror.com/primary-keys-ids-versus-guids/
> this is about using guid as primary key which i cannot use now as many
> rails gems are tied to integer primary key. mongodb and other nosql dbs
> uses this kind of keys as(_id) so it works great in distributed models. but
> relational db it may or may not be good fit. there are pros and cons of
> both. lets close this issue right now
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/barterli/barter.li/issues/32#issuecomment-38905204
> .

## 

Vinay S Shenoy
Software Engineer | Sourcebits LLC, Electronic City, Bangalore
+91-9538122356 | vinaysshenoy@gmail.com
LinkedIn : http://in.linkedin.com/in/vinaysshenoy

**Comment by suras** [comment]
i am removing the id part

**Comment by vinaysshenoy** [comment]
Great. :-)

On Fri, Mar 28, 2014 at 4:03 PM, surendar notifications@github.com wrote:

> i am removing the id part
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/barterli/barter.li/issues/32#issuecomment-38905816
> .

## 

Vinay S Shenoy
Software Engineer | Sourcebits LLC, Electronic City, Bangalore
+91-9538122356 | vinaysshenoy@gmail.com
LinkedIn : http://in.linkedin.com/in/vinaysshenoy
