### ISSUE TITLE
public controller issues

### ISSUE THREAD

**Issue by sourcebits-ajmal** [barterli/barter.li#33]
public controller gives, circular dependency errors,
but when changed to (api1:v1) namespace, its gone, but there are issues on welcome layout.

Is it still used?

**Comment by suras** [comment]
no view layer is used and no layouts used. controller is inherited from ActionController::API

**Comment by sourcebits-ajmal** [comment]
So the publiccontroller is in use?

I got the following bug

# RuntimeError at /api/v1/register

> Circular dependency detected while autoloading constant Api::V1::PublicController

## activesupport (4.0.2) lib/active_support/dependencies.rb, line 461

``` ruby
  456         if file_path
  457           expanded = File.expand_path(file_path)
  458           expanded.sub!(/\.rb\z/, '')
  459   
  460           if loaded.include?(expanded)
> 461             raise "Circular dependency detected while autoloading constant #{qualified_name}"
  462           else
  463             require_or_load(expanded, qualified_name)
  464             raise LoadError, "Unable to autoload constant #{qualified_name}, expected #{file_path} to define it" unless from_mod.const_defined?(const_name, false)
  465             return from_mod.const_get(const_name)
  466           end
```

## App backtrace

## Full backtrace
- activesupport (4.0.2) lib/active_support/dependencies.rb:461:in `load_missing_constant'
- activesupport (4.0.2) lib/active_support/dependencies.rb:184:in `const_missing'
- activesupport (4.0.2) lib/active_support/inflector/methods.rb:241:in `block in constantize'
- activesupport (4.0.2) lib/active_support/inflector/methods.rb:224:in `constantize'
- activesupport (4.0.2) lib/active_support/dependencies.rb:535:in `get'
- activesupport (4.0.2) lib/active_support/dependencies.rb:566:in `constantize'
- actionpack (4.0.2) lib/action_dispatch/routing/route_set.rb:76:in `controller_reference'
- actionpack (4.0.2) lib/action_dispatch/routing/route_set.rb:66:in `controller'
- actionpack (4.0.2) lib/action_dispatch/routing/route_set.rb:44:in `call'
- actionpack (4.0.2) lib/action_dispatch/journey/router.rb:71:in `block in call'
- actionpack (4.0.2) lib/action_dispatch/journey/router.rb:59:in `call'
- actionpack (4.0.2) lib/action_dispatch/routing/route_set.rb:680:in `call'
- omniauth (1.1.4) lib/omniauth/strategy.rb:184:in `call!'
- omniauth (1.1.4) lib/omniauth/strategy.rb:164:in `call'
- omniauth (1.1.4) lib/omniauth/strategy.rb:184:in `call!'
- omniauth (1.1.4) lib/omniauth/strategy.rb:164:in `call'
- warden (1.2.3) lib/warden/manager.rb:35:in `block in call'
- warden (1.2.3) lib/warden/manager.rb:34:in `call'
- rack (1.5.2) lib/rack/etag.rb:23:in `call'
- rack (1.5.2) lib/rack/conditionalget.rb:35:in `call'
- rack (1.5.2) lib/rack/head.rb:11:in `call'
- actionpack (4.0.2) lib/action_dispatch/middleware/params_parser.rb:27:in `call'
- actionpack (4.0.2) lib/action_dispatch/middleware/flash.rb:241:in `call'
- rack (1.5.2) lib/rack/session/abstract/id.rb:225:in `context'
- rack (1.5.2) lib/rack/session/abstract/id.rb:220:in `call'
- actionpack (4.0.2) lib/action_dispatch/middleware/cookies.rb:486:in `call'
- activerecord (4.0.2) lib/active_record/query_cache.rb:36:in `call'
- activerecord (4.0.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:626:in `call'
- activerecord (4.0.2) lib/active_record/migration.rb:369:in `call'
- actionpack (4.0.2) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
- activesupport (4.0.2) lib/active_support/callbacks.rb:373:in `_run__1068227961__call__callbacks'
- activesupport (4.0.2) lib/active_support/callbacks.rb:80:in `run_callbacks'
- actionpack (4.0.2) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
- actionpack (4.0.2) lib/action_dispatch/middleware/reloader.rb:64:in `call'
- actionpack (4.0.2) lib/action_dispatch/middleware/remote_ip.rb:76:in `call'
- better_errors (1.0.1) lib/better_errors/middleware.rb:84:in `protected_app_call'
- better_errors (1.0.1) lib/better_errors/middleware.rb:79:in `better_errors_call'
- better_errors (1.0.1) lib/better_errors/middleware.rb:56:in `call'
- actionpack (4.0.2) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
- actionpack (4.0.2) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
- railties (4.0.2) lib/rails/rack/logger.rb:38:in `call_app'
- railties (4.0.2) lib/rails/rack/logger.rb:20:in `block in call'
- activesupport (4.0.2) lib/active_support/tagged_logging.rb:67:in `block in tagged'
- activesupport (4.0.2) lib/active_support/tagged_logging.rb:25:in `tagged'
- activesupport (4.0.2) lib/active_support/tagged_logging.rb:67:in `tagged'
- railties (4.0.2) lib/rails/rack/logger.rb:20:in `call'
- quiet_assets (1.0.2) lib/quiet_assets.rb:18:in `call_with_quiet_assets'
- actionpack (4.0.2) lib/action_dispatch/middleware/request_id.rb:21:in `call'
- rack (1.5.2) lib/rack/methodoverride.rb:21:in `call'
- rack (1.5.2) lib/rack/runtime.rb:17:in `call'
- rack (1.5.2) lib/rack/lock.rb:17:in `call'
- actionpack (4.0.2) lib/action_dispatch/middleware/static.rb:64:in `call'
- rack (1.5.2) lib/rack/sendfile.rb:112:in `call'
- railties (4.0.2) lib/rails/engine.rb:511:in `call'
- railties (4.0.2) lib/rails/application.rb:97:in `call'
- rack (1.5.2) lib/rack/content_length.rb:14:in `call'
- thin (1.5.1) lib/thin/connection.rb:81:in `block in pre_process'
- thin (1.5.1) lib/thin/connection.rb:79:in `pre_process'
- thin (1.5.1) lib/thin/connection.rb:54:in `process'
- thin (1.5.1) lib/thin/connection.rb:39:in `receive_data'
- eventmachine (1.0.3) lib/eventmachine.rb:187:in `run'
- thin (1.5.1) lib/thin/backends/base.rb:63:in `start'
- thin (1.5.1) lib/thin/server.rb:159:in `start'
- rack (1.5.2) lib/rack/handler/thin.rb:16:in `run'
- rack (1.5.2) lib/rack/server.rb:264:in `start'
- railties (4.0.2) lib/rails/commands/server.rb:84:in `start'
- railties (4.0.2) lib/rails/commands.rb:76:in `block in 
  <top (required)>'
- railties (4.0.2) lib/rails/commands.rb:71:in `
  <top (required)>'
- bin/rails:4:in `
      <main>'

**Comment by suras** [comment]
which branch are you using. 
check whether the class name is Api::V1::PublicController. i forgot to add api::v1 namespace. check whether there are two publiccontroller files.  its working fine now. but i never got circular dependency error

**Comment by sourcebits-ajmal** [comment]
yes its development only,
like I said, when I added Api::v1, i got errors for rendering the welcome layout

**Comment by suras** [comment]
v capital there will be no rendering only json response.
![register](https://cloud.githubusercontent.com/assets/3854470/2535831/c82aa51a-b594-11e3-80f0-7c956129c09a.png)
