### ISSUE TITLE
Send authentication token in http request header

### ISSUE THREAD

**Issue by vinaysshenoy** [barterli/barter.li#35]
We need to send the authentication token in request header. We can use AUTHORIZATION key, and you can extract it from headers instead of body. With this, I can automatically add auth token to all requests, and you can pick it up from whichever requests need it. Otherwise, I need to manually add add the requests which could lead to problems.

**Comment by suras** [comment]
yes i will work on it

**Comment by suras** [comment]
yes done it i have used http token authentication
Authorization Token token="TRU2uUh1DxfyTdi3tnEs", email="test@gmail.com"

i have used email because for the purpose of finding user by email and secure comparing the auth token. this eliminates the possibility of timing attack

**Comment by vinaysshenoy** [comment]
Alright.

One modification request, instead of passing email, can we pass the user ID
instead? It doesn't feel good passing email in every request. :-)

On Fri, Mar 28, 2014 at 2:34 PM, surendar notifications@github.com wrote:

> yes done it i have used http token authentication
> Authorization Token token="TRU2uUh1DxfyTdi3tnEs", email="test@gmail.com"
> 
> i have used email because for the purpose of finding user by email and
> secure comparing the auth token. this eliminates the possibility of timing
> attack
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/barterli/barter.li/issues/35#issuecomment-38899510
> .

## 

Vinay S Shenoy
Software Engineer | Sourcebits LLC, Electronic City, Bangalore
+91-9538122356 | vinaysshenoy@gmail.com
LinkedIn : http://in.linkedin.com/in/vinaysshenoy

**Comment by suras** [comment]
normally email is used in this cases not ids.

**Comment by vinaysshenoy** [comment]
Can you point me to some documentation where this is mentioned? In every
web service I've integrated so far, email is used only when sign in, create
user or reset password.

For others, they only require the auth token, nothing else.

**Comment by suras** [comment]
sending unique id may me too much revealing details and a security concern.

**Comment by vinaysshenoy** [comment]
How is it a bigger security concern then sending email? Revealing the
user's email id is worse than that. This is will be the same GUID generated
for the user anyway.

On Fri, Mar 28, 2014 at 3:35 PM, surendar notifications@github.com wrote:

> sending unique id may me too much revealing details and a security
> concern.
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/barterli/barter.li/issues/35#issuecomment-38903678
> .

## 

Vinay S Shenoy
Software Engineer | Sourcebits LLC, Electronic City, Bangalore
+91-9538122356 | vinaysshenoy@gmail.com
LinkedIn : http://in.linkedin.com/in/vinaysshenoy

**Comment by suras** [comment]
if we are not using primary key then it is not a concern.   email or guid is only a matter of choice.

**Comment by vinaysshenoy** [comment]
Alright. we'll go with a guid. But can you add some documentation about
this timing attack? This seems to be something new.

On Fri, Mar 28, 2014 at 4:00 PM, surendar notifications@github.com wrote:

> if we are not using primary key then it is not a concern. email or guid is
> only a matter of choice.
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/barterli/barter.li/issues/35#issuecomment-38905570
> .

## 

Vinay S Shenoy
Software Engineer | Sourcebits LLC, Electronic City, Bangalore
+91-9538122356 | vinaysshenoy@gmail.com
LinkedIn : http://in.linkedin.com/in/vinaysshenoy

**Comment by suras** [comment]
since guid is part of some discussion we can go with email.  devise gem example implementation is based on email and token

**Comment by vinaysshenoy** [comment]
Agreed.

**Comment by suras** [comment]
timing attack explanation 

http://codahale.com/a-lesson-in-timing-attacks/
